// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pubnub.types.proto

package pubnub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishResponse_Status int32

const (
	PublishResponse_SUCCESS PublishResponse_Status = 0
	PublishResponse_ERROR   PublishResponse_Status = 1
)

var PublishResponse_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
}

var PublishResponse_Status_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
}

func (x PublishResponse_Status) String() string {
	return proto.EnumName(PublishResponse_Status_name, int32(x))
}

func (PublishResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c379163f5b17d00, []int{1, 0}
}

type Subscription struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c379163f5b17d00, []int{0}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type PublishResponse struct {
	Message              string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timetoken            *Timetoken             `protobuf:"bytes,2,opt,name=timetoken,proto3" json:"timetoken,omitempty"`
	Status               PublishResponse_Status `protobuf:"varint,3,opt,name=status,proto3,enum=pubnub.PublishResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c379163f5b17d00, []int{1}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PublishResponse) GetTimetoken() *Timetoken {
	if m != nil {
		return m.Timetoken
	}
	return nil
}

func (m *PublishResponse) GetStatus() PublishResponse_Status {
	if m != nil {
		return m.Status
	}
	return PublishResponse_SUCCESS
}

type Timetoken struct {
	T                    uint64   `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	R                    uint32   `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timetoken) Reset()         { *m = Timetoken{} }
func (m *Timetoken) String() string { return proto.CompactTextString(m) }
func (*Timetoken) ProtoMessage()    {}
func (*Timetoken) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c379163f5b17d00, []int{2}
}

func (m *Timetoken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timetoken.Unmarshal(m, b)
}
func (m *Timetoken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timetoken.Marshal(b, m, deterministic)
}
func (m *Timetoken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timetoken.Merge(m, src)
}
func (m *Timetoken) XXX_Size() int {
	return xxx_messageInfo_Timetoken.Size(m)
}
func (m *Timetoken) XXX_DiscardUnknown() {
	xxx_messageInfo_Timetoken.DiscardUnknown(m)
}

var xxx_messageInfo_Timetoken proto.InternalMessageInfo

func (m *Timetoken) GetT() uint64 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *Timetoken) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

type Location struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c379163f5b17d00, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterEnum("pubnub.PublishResponse_Status", PublishResponse_Status_name, PublishResponse_Status_value)
	proto.RegisterType((*Subscription)(nil), "pubnub.Subscription")
	proto.RegisterType((*PublishResponse)(nil), "pubnub.PublishResponse")
	proto.RegisterType((*Timetoken)(nil), "pubnub.Timetoken")
	proto.RegisterType((*Location)(nil), "pubnub.Location")
}

func init() { proto.RegisterFile("pubnub.types.proto", fileDescriptor_0c379163f5b17d00) }

var fileDescriptor_0c379163f5b17d00 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xc3, 0x30,
	0x10, 0x44, 0x71, 0x80, 0xb4, 0xd9, 0x16, 0x28, 0x3e, 0x45, 0x08, 0xa1, 0x28, 0x17, 0x72, 0x0a,
	0x52, 0x91, 0xf8, 0x81, 0xd2, 0x1b, 0x12, 0x68, 0x03, 0x1f, 0x10, 0x07, 0xab, 0xb5, 0x48, 0x6d,
	0x2b, 0x5e, 0x1f, 0xf8, 0x31, 0xbe, 0x0f, 0xd5, 0x49, 0x5a, 0xa9, 0xc7, 0x99, 0x79, 0xd2, 0xce,
	0x0e, 0x70, 0xeb, 0x85, 0xf6, 0xa2, 0xa4, 0x5f, 0x2b, 0x5d, 0x69, 0x3b, 0x43, 0x86, 0xc7, 0xbd,
	0x97, 0x17, 0x30, 0xaf, 0xbc, 0x70, 0x4d, 0xa7, 0x2c, 0x29, 0xa3, 0x79, 0x0a, 0x93, 0x66, 0x5b,
	0x6b, 0x2d, 0xdb, 0x94, 0x65, 0xac, 0x48, 0x70, 0x94, 0xf9, 0x1f, 0x83, 0x9b, 0x0f, 0x2f, 0x5a,
	0xe5, 0xb6, 0x28, 0x9d, 0x35, 0xda, 0xc9, 0x3d, 0xbd, 0x93, 0xce, 0xd5, 0x1b, 0x39, 0xd2, 0x83,
	0xe4, 0x4f, 0x90, 0x90, 0xda, 0x49, 0x32, 0x3f, 0x52, 0xa7, 0x51, 0xc6, 0x8a, 0xd9, 0xf2, 0xb6,
	0x1c, 0x7a, 0x7c, 0x8e, 0x01, 0x1e, 0x19, 0xfe, 0x02, 0xb1, 0xa3, 0x9a, 0xbc, 0x4b, 0xcf, 0x33,
	0x56, 0x5c, 0x2f, 0x1f, 0x46, 0xfa, 0xe4, 0x66, 0x59, 0x05, 0x0a, 0x07, 0x3a, 0xcf, 0x20, 0xee,
	0x1d, 0x3e, 0x83, 0x49, 0xf5, 0xb5, 0x5a, 0xad, 0xab, 0x6a, 0x71, 0xc6, 0x13, 0xb8, 0x5c, 0x23,
	0xbe, 0xe3, 0x82, 0xe5, 0x8f, 0x90, 0x1c, 0x2e, 0xf2, 0x39, 0x30, 0x0a, 0x5d, 0x2f, 0x90, 0xd1,
	0x5e, 0x75, 0xa1, 0xdd, 0x15, 0xb2, 0x2e, 0x7f, 0x85, 0xe9, 0x9b, 0x69, 0xea, 0xb0, 0xc3, 0x1d,
	0x4c, 0xdb, 0x9a, 0x14, 0xf9, 0xef, 0xfe, 0xb5, 0x08, 0x0f, 0x9a, 0xdf, 0x43, 0xd2, 0x1a, 0xbd,
	0xe9, 0xc3, 0x28, 0x84, 0x47, 0x43, 0xc4, 0x61, 0xe0, 0xe7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0xd2, 0x52, 0xe8, 0x76, 0x01, 0x00, 0x00,
}
